Repository jupyterlab/ui-profiler, pull requests merged in 2023-04, with the labels that each got.

#40 Fix token identifier
  src/tokens.ts
Labels: bug

#42 Fixed README.md User Guide link
  README.md
Labels: documentation

#43 Ensure the results directory is created before saving results
  src/ui.tsx
  ui-tests/tests/profiler.spec.ts
  ui-tests/tests/results.spec.ts
Labels: bug

#44 Use `_version.py` auto-generated by Hatchling
  .gitignore
  jupyterlab_ui_profiler/_version.py
  pyproject.toml
Labels: bug

#46 Separate profiler out of the user interface
  src/benchmark.ts
  src/browserProfiler.d.ts
  src/index.ts
  src/jsBenchmarks.ts
  src/profiler.ts
  src/styleBenchmarks.tsx
  src/table.ts
  src/tokens.ts
  src/ui.tsx
  src/utils.ts
Labels: enhancement

#48 Allow to open editor in the same area to support small screens
  src/dramaturg.ts
  src/scenarios.ts
  src/schema/scenario-completer.json
  src/schema/scenario-debugger.json
  src/schema/scenario-scroll.json
  src/types/_scenario-completer.ts
  src/types/_scenario-debugger.ts
  src/types/_scenario-scroll.ts
Labels: bug

#49 Expose option types for more convenient use downstream
  src/benchmark.ts
  src/index.ts
  src/jsBenchmarks.ts
  src/scenarios.ts
  src/styleBenchmarks.tsx
  src/types/index.ts
Labels: enhancement
